{{- if .Values.autoinstrumentation.enabled -}}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: openobserve-python
  namespace: {{ .Release.Namespace | quote }}
spec:
  exporter:
    endpoint: http://{{ include "openobserve-collector.fullname" . }}-gateway-collector.{{ .Release.Namespace }}.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: http/protobuf
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: http/protobuf
      - name: OTEL_LOGS_EXPORTER
        value: otlp_proto_http
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: "false" # set to true to enable auto instrumentation for logs
  
{{- end }}
