apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-router
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc_port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "openobserve.selectorLabels" . | nindent 4 }}
    role: router
