{{- if and .Values.enterprise.enabled .Values.enterprise.scriptserver.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openobserve.serviceAccountName" . }}-scriptserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 