apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zincobserve.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zincobserve.labels" . | nindent 4 }}
data:
  ZO_LOCAL_MODE: "{{ .Values.config.ZO_LOCAL_MODE }}"
  {{- if not .Values.etcd.bundled }}
  ZO_ETCD_ADDR: "{{ .Values.etcd.externalUrl }}"
  {{- else }}
  ZO_ETCD_ADDR: "{{ .Release.Name }}-etcd-headless.{{ .Release.Namespace }}.svc.cluster.local:2379"
  {{- end }}
  ZO_GRPC_PORT: "{{ .Values.config.ZO_GRPC_PORT }}"
  ZO_GRPC_TIMEOUT: "{{ .Values.config.ZO_GRPC_TIMEOUT }}"
  ZO_GRPC_ORG_HEADER_KEY: "{{ .Values.config.ZO_GRPC_ORG_HEADER_KEY }}"
  ZO_ROUTE_TIMEOUT: "{{ .Values.config.ZO_ROUTE_TIMEOUT }}"
  ZO_LOCAL_MODE_STORAGE: "{{ .Values.config.ZO_LOCAL_MODE_STORAGE }}"
  ZO_NODE_ROLE: "{{ .Values.config.ZO_NODE_ROLE }}"
  ZO_INSTANCE_NAME: "{{ .Values.config.ZO_INSTANCE_NAME }}"
  ZO_DATA_DIR: "{{ .Values.config.ZO_DATA_DIR }}"
  ZO_DATA_WAL_DIR: "{{ .Values.config.ZO_DATA_WAL_DIR }}"
  ZO_DATA_STREAM_DIR: "{{ .Values.config.ZO_DATA_STREAM_DIR }}"
  ZO_WAL_MEMORY_MODE_ENABLED: "{{ .Values.config.ZO_WAL_MEMORY_MODE_ENABLED }}"
  ZO_FILE_EXT_JSON: "{{ .Values.config.ZO_FILE_EXT_JSON }}"
  ZO_FILE_EXT_PARQUET: "{{ .Values.config.ZO_FILE_EXT_PARQUET }}"
  ZO_PARQUET_COMPRESSION: "{{ .Values.config.ZO_PARQUET_COMPRESSION }}"
  ZO_TIME_STAMP_COL: "{{ .Values.config.ZO_TIME_STAMP_COL }}"
  ZO_WIDENING_SCHEMA_EVOLUTION: "{{ .Values.config.ZO_WIDENING_SCHEMA_EVOLUTION }}"
  ZO_FEATURE_PER_THREAD_LOCK: "{{ .Values.config.ZO_FEATURE_PER_THREAD_LOCK }}"
  ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS: "{{ .Values.config.ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS }}"
  ZO_UI_ENABLED: "{{ .Values.config.ZO_UI_ENABLED }}"
  ZO_METRICS_DEDUP_ENABLED: "{{ .Values.config.ZO_METRICS_DEDUP_ENABLED }}"
  ZO_TRACING_ENABLED: "{{ .Values.config.ZO_TRACING_ENABLED }}"
  OTEL_OTLP_HTTP_ENDPOINT: "{{ .Values.config.OTEL_OTLP_HTTP_ENDPOINT }}"
  ZO_TRACING_HEADER_KEY: "{{ .Values.config.ZO_TRACING_HEADER_KEY }}"
  ZO_TRACING_HEADER_VALUE: "{{ .Values.config.ZO_TRACING_HEADER_VALUE }}"
  ZO_TELEMETRY: "{{ .Values.config.ZO_TELEMETRY }}"
  ZO_TELEMETRY_URL: "{{ .Values.config.ZO_TELEMETRY_URL }}"
  ZO_JSON_LIMIT: "{{ .Values.config.ZO_JSON_LIMIT }}"
  ZO_PAYLOAD_LIMIT: "{{ .Values.config.ZO_PAYLOAD_LIMIT }}"
  ZO_MAX_FILE_SIZE_ON_DISK: "{{ .Values.config.ZO_MAX_FILE_SIZE_ON_DISK }}"
  ZO_MAX_FILE_RETENTION_TIME: "{{ .Values.config.ZO_MAX_FILE_RETENTION_TIME }}"
  ZO_FILE_PUSH_INTERVAL: "{{ .Values.config.ZO_FILE_PUSH_INTERVAL }}"
  ZO_FILE_MOVE_THREAD_NUM: "{{ .Values.config.ZO_FILE_MOVE_THREAD_NUM }}"
  ZO_QUERY_THREAD_NUM: "{{ .Values.config.ZO_QUERY_THREAD_NUM }}"
  ZO_TS_ALLOWED_UPTO: "{{ .Values.config.ZO_TS_ALLOWED_UPTO }}"
  ZO_METRICS_LEADER_PUSH_INTERVAL: "{{ .Values.config.ZO_METRICS_LEADER_PUSH_INTERVAL }}"
  ZO_METRICS_LEADER_ELECTION_INTERVAL: "{{ .Values.config.ZO_METRICS_LEADER_ELECTION_INTERVAL }}"
  ZO_HEARTBEAT_INTERVAL: "{{ .Values.config.ZO_HEARTBEAT_INTERVAL }}"
  ZO_COMPACT_ENABLED: "{{ .Values.config.ZO_COMPACT_ENABLED }}"
  ZO_COMPACT_INTERVAL: "{{ .Values.config.ZO_COMPACT_INTERVAL }}"
  ZO_COMPACT_MAX_FILE_SIZE: "{{ .Values.config.ZO_COMPACT_MAX_FILE_SIZE }}"
  ZO_MEMORY_CACHE_ENABLED: "{{ .Values.config.ZO_MEMORY_CACHE_ENABLED }}"
  ZO_MEMORY_CACHE_CACHE_LATEST_FILES: "{{ .Values.config.ZO_MEMORY_CACHE_CACHE_LATEST_FILES }}"
  ZO_MEMORY_CACHE_MAX_SIZE: "{{ .Values.config.ZO_MEMORY_CACHE_MAX_SIZE }}"
  ZO_MEMORY_CACHE_RELEASE_SIZE: "{{ .Values.config.ZO_MEMORY_CACHE_RELEASE_SIZE }}"
  RUST_LOG: "{{ .Values.config.RUST_LOG }}"
  ZO_COLS_PER_RECORD_LIMIT: "{{ .Values.config.ZO_COLS_PER_RECORD_LIMIT }}"
  ZO_ETCD_PREFIX: "{{ .Values.config.ZO_ETCD_PREFIX }}"
  ZO_ETCD_CONNECT_TIMEOUT: "{{ .Values.config.ZO_ETCD_CONNECT_TIMEOUT }}"
  ZO_ETCD_COMMAND_TIMEOUT: "{{ .Values.config.ZO_ETCD_COMMAND_TIMEOUT }}"
  ZO_ETCD_LOCK_WAIT_TIMEOUT: "{{ .Values.config.ZO_ETCD_LOCK_WAIT_TIMEOUT }}"
  ZO_ETCD_USER: "{{ .Values.config.ZO_ETCD_USER }}"
  ZO_ETCD_PASSWORD: "{{ .Values.config.ZO_ETCD_PASSWORD }}"
  ZO_ETCD_CLIENT_CERT_AUTH: "{{ .Values.config.ZO_ETCD_CLIENT_CERT_AUTH }}"
  ZO_ETCD_TRUSTED_CA_FILE: "{{ .Values.config.ZO_ETCD_TRUSTED_CA_FILE }}"
  ZO_ETCD_CERT_FILE: "{{ .Values.config.ZO_ETCD_CERT_FILE }}"
  ZO_ETCD_KEY_FILE: "{{ .Values.config.ZO_ETCD_KEY_FILE }}"
  ZO_ETCD_DOMAIN_NAME: "{{ .Values.config.ZO_ETCD_DOMAIN_NAME }}"
  ZO_ETCD_LOAD_PAGE_SIZE: "{{ .Values.config.ZO_ETCD_LOAD_PAGE_SIZE }}"
  ZO_SLED_DATA_DIR: "{{ .Values.config.ZO_SLED_DATA_DIR }}"
  ZO_SLED_PREFIX: "{{ .Values.config.ZO_SLED_PREFIX }}"
  ZO_S3_SERVER_URL: "{{ .Values.config.ZO_S3_SERVER_URL }}"
  ZO_S3_REGION_NAME: "{{ .Values.config.ZO_S3_REGION_NAME }}"
  ZO_S3_ACCESS_KEY: "{{ .Values.config.ZO_S3_ACCESS_KEY }}"
  ZO_S3_SECRET_KEY: "{{ .Values.config.ZO_S3_SECRET_KEY }}"
  ZO_S3_BUCKET_NAME: "{{ .Values.config.ZO_S3_BUCKET_NAME }}"
