apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openobserve.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
data:
  ZO_LOCAL_MODE: "{{ .Values.config.ZO_LOCAL_MODE }}"
  ZO_LOCAL_MODE_STORAGE: "{{ .Values.config.ZO_LOCAL_MODE_STORAGE }}"
  {{- if not .Values.etcd.enabled }}
  ZO_ETCD_ADDR: "{{ .Values.etcd.externalUrl }}"
  {{- else }}
  ZO_ETCD_ADDR: "{{ .Release.Name }}-etcd-headless.{{ .Release.Namespace }}.svc.cluster.local:2379"
  {{- end }}
  ZO_HTTP_PORT: "{{ .Values.config.ZO_HTTP_PORT }}"
  ZO_HTTP_ADDR: "{{ .Values.config.ZO_HTTP_ADDR }}"
  ZO_HTTP_IPV6_ENABLED: "{{ .Values.config.ZO_HTTP_IPV6_ENABLED }}"
  ZO_GRPC_PORT: "{{ .Values.config.ZO_GRPC_PORT }}"
  ZO_GRPC_ADDR: "{{ .Values.config.ZO_GRPC_ADDR }}"
  ZO_GRPC_TIMEOUT: "{{ .Values.config.ZO_GRPC_TIMEOUT }}"
  ZO_GRPC_ORG_HEADER_KEY: "{{ .Values.config.ZO_GRPC_ORG_HEADER_KEY }}"
  ZO_ROUTE_TIMEOUT: "{{ .Values.config.ZO_ROUTE_TIMEOUT }}"
  ZO_INSTANCE_NAME: "{{ .Values.config.ZO_INSTANCE_NAME }}"
  ZO_DATA_DIR: "{{ .Values.config.ZO_DATA_DIR }}"
  ZO_DATA_DB_DIR: "{{ .Values.config.ZO_DATA_DB_DIR }}"
  ZO_DATA_WAL_DIR: "{{ .Values.config.ZO_DATA_WAL_DIR }}"
  ZO_DATA_STREAM_DIR: "{{ .Values.config.ZO_DATA_STREAM_DIR }}"
  ZO_DATA_CACHE_DIR: "{{ .Values.config.ZO_DATA_CACHE_DIR }}"
  ZO_UI_ENABLED: "{{ .Values.config.ZO_UI_ENABLED }}"
  ZO_BASE_URI: "{{ .Values.config.ZO_BASE_URI }}"
  ZO_META_STORE: "{{ .Values.config.ZO_META_STORE }}"
  ZO_META_DYNAMO_PREFIX: "{{ .Values.config.ZO_META_DYNAMO_PREFIX }}"
  ZO_META_POSTGRES_DSN: "{{ .Values.config.ZO_META_POSTGRES_DSN }}"
  ZO_WAL_MEMORY_MODE_ENABLED: "{{ .Values.config.ZO_WAL_MEMORY_MODE_ENABLED }}"
  ZO_WAL_LINE_MODE_ENABLED: "{{ .Values.config.ZO_WAL_LINE_MODE_ENABLED }}"
  ZO_PARQUET_COMPRESSION: "{{ .Values.config.ZO_PARQUET_COMPRESSION }}"
  ZO_COLUMN_TIMESTAMP: "{{ .Values.config.ZO_COLUMN_TIMESTAMP }}"
  ZO_COLS_PER_RECORD_LIMIT: "{{ .Values.config.ZO_COLS_PER_RECORD_LIMIT }}"
  ZO_WIDENING_SCHEMA_EVOLUTION: "{{ .Values.config.ZO_WIDENING_SCHEMA_EVOLUTION }}"
  ZO_SKIP_SCHEMA_VALIDATION: "{{ .Values.config.ZO_SKIP_SCHEMA_VALIDATION }}"
  ZO_FEATURE_PER_THREAD_LOCK: "{{ .Values.config.ZO_FEATURE_PER_THREAD_LOCK }}"
  ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS: "{{ .Values.config.ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS }}"
  ZO_FEATURE_FULLTEXT_EXTRA_FIELDS: "{{ .Values.config.ZO_FEATURE_FULLTEXT_EXTRA_FIELDS }}"
  ZO_TRACES_BLOOM_FILTER_ENABLED: "{{ .Values.config.ZO_TRACES_BLOOM_FILTER_ENABLED }}"
  ZO_TRACING_ENABLED: "{{ .Values.config.ZO_TRACING_ENABLED }}"
  ZO_TRACING_HEADER_KEY: "{{ .Values.config.ZO_TRACING_HEADER_KEY }}"
  ZO_TRACING_HEADER_VALUE: "{{ .Values.config.ZO_TRACING_HEADER_VALUE }}"
  OTEL_OTLP_HTTP_ENDPOINT: "{{ .Values.config.OTEL_OTLP_HTTP_ENDPOINT }}"
  ZO_TELEMETRY: "{{ .Values.config.ZO_TELEMETRY }}"
  ZO_TELEMETRY_URL: "{{ .Values.config.ZO_TELEMETRY_URL }}"
  ZO_HEARTBEAT_INTERVAL: "{{ .Values.config.ZO_HEARTBEAT_INTERVAL }}"
  ZO_JSON_LIMIT: "{{ .Values.config.ZO_JSON_LIMIT }}"
  ZO_PAYLOAD_LIMIT: "{{ .Values.config.ZO_PAYLOAD_LIMIT }}"
  ZO_MAX_FILE_SIZE_ON_DISK: "{{ .Values.config.ZO_MAX_FILE_SIZE_ON_DISK }}"
  ZO_MAX_FILE_RETENTION_TIME: "{{ .Values.config.ZO_MAX_FILE_RETENTION_TIME }}"
  ZO_FILE_PUSH_INTERVAL: "{{ .Values.config.ZO_FILE_PUSH_INTERVAL }}"
  ZO_FILE_MOVE_THREAD_NUM: "{{ .Values.config.ZO_FILE_MOVE_THREAD_NUM }}"
  ZO_QUERY_THREAD_NUM: "{{ .Values.config.ZO_QUERY_THREAD_NUM }}"
  ZO_QUERY_TIMEOUT: "{{ .Values.config.ZO_QUERY_TIMEOUT }}"
  ZO_HTTP_WORKER_NUM: "{{ .Values.config.ZO_HTTP_WORKER_NUM }}"
  ZO_HTTP_WORKER_MAX_BLOCKING: "{{ .Values.config.ZO_HTTP_WORKER_MAX_BLOCKING }}"
  ZO_INGEST_ALLOWED_UPTO: "{{ .Values.config.ZO_INGEST_ALLOWED_UPTO }}"
  ZO_LOGS_FILE_RETENTION: "{{ .Values.config.ZO_LOGS_FILE_RETENTION }}"
  ZO_TRACES_FILE_RETENTION: "{{ .Values.config.ZO_TRACES_FILE_RETENTION }}"
  ZO_METRICS_FILE_RETENTION: "{{ .Values.config.ZO_METRICS_FILE_RETENTION }}"
  ZO_METRICS_DEDUP_ENABLED: "{{ .Values.config.ZO_METRICS_DEDUP_ENABLED }}"
  ZO_METRICS_LEADER_PUSH_INTERVAL: "{{ .Values.config.ZO_METRICS_LEADER_PUSH_INTERVAL }}"
  ZO_METRICS_LEADER_ELECTION_INTERVAL: "{{ .Values.config.ZO_METRICS_LEADER_ELECTION_INTERVAL }}"
  ZO_PROMETHEUS_HA_CLUSTER: "{{ .Values.config.ZO_PROMETHEUS_HA_CLUSTER }}"
  ZO_PROMETHEUS_HA_REPLICA: "{{ .Values.config.ZO_PROMETHEUS_HA_REPLICA }}"
  ZO_COMPACT_ENABLED: "{{ .Values.config.ZO_COMPACT_ENABLED }}"
  ZO_COMPACT_FAKE_MODE: "{{ .Values.config.ZO_COMPACT_FAKE_MODE }}"
  ZO_COMPACT_INTERVAL: "{{ .Values.config.ZO_COMPACT_INTERVAL }}"
  ZO_COMPACT_SYNC_TO_DB_INTERVAL: "{{ .Values.config.ZO_COMPACT_SYNC_TO_DB_INTERVAL }}"
  ZO_COMPACT_MAX_FILE_SIZE: "{{ .Values.config.ZO_COMPACT_MAX_FILE_SIZE }}"
  ZO_COMPACT_DATA_RETENTION_DAYS: "{{ .Values.config.ZO_COMPACT_DATA_RETENTION_DAYS }}"
  ZO_COMPACT_BLOCKED_ORGS: "{{ .Values.config.ZO_COMPACT_BLOCKED_ORGS }}"
  ZO_MEMORY_CACHE_ENABLED: "{{ .Values.config.ZO_MEMORY_CACHE_ENABLED }}"
  ZO_MEMORY_CACHE_CACHE_LATEST_FILES: "{{ .Values.config.ZO_MEMORY_CACHE_CACHE_LATEST_FILES }}"
  ZO_MEMORY_CACHE_MAX_SIZE: "{{ .Values.config.ZO_MEMORY_CACHE_MAX_SIZE }}"
  ZO_MEMORY_CACHE_SKIP_SIZE: "{{ .Values.config.ZO_MEMORY_CACHE_SKIP_SIZE }}"
  ZO_MEMORY_CACHE_RELEASE_SIZE: "{{ .Values.config.ZO_MEMORY_CACHE_RELEASE_SIZE }}"
  ZO_MEMORY_CACHE_DATAFUSION_MEMORY_POOL: "{{ .Values.config.ZO_MEMORY_CACHE_DATAFUSION_MEMORY_POOL }}"
  ZO_MEMORY_CACHE_DATAFUSION_MAX_SIZE: "{{ .Values.config.ZO_MEMORY_CACHE_DATAFUSION_MAX_SIZE }}"
  ZO_DISK_CACHE_ENABLED: "{{ .Values.config.ZO_DISK_CACHE_ENABLED }}"
  ZO_DISK_CACHE_MAX_SIZE: "{{ .Values.config.ZO_DISK_CACHE_MAX_SIZE }}"
  ZO_DISK_CACHE_SKIP_SIZE: "{{ .Values.config.ZO_DISK_CACHE_SKIP_SIZE }}"
  ZO_DISK_CACHE_RELEASE_SIZE: "{{ .Values.config.ZO_DISK_CACHE_RELEASE_SIZE }}"
  ZO_ETCD_PREFIX: "{{ .Values.config.ZO_ETCD_PREFIX }}"
  ZO_ETCD_CONNECT_TIMEOUT: "{{ .Values.config.ZO_ETCD_CONNECT_TIMEOUT }}"
  ZO_ETCD_COMMAND_TIMEOUT: "{{ .Values.config.ZO_ETCD_COMMAND_TIMEOUT }}"
  ZO_ETCD_LOCK_WAIT_TIMEOUT: "{{ .Values.config.ZO_ETCD_LOCK_WAIT_TIMEOUT }}"
  ZO_ETCD_USER: "{{ .Values.config.ZO_ETCD_USER }}"
  ZO_ETCD_PASSWORD: "{{ .Values.config.ZO_ETCD_PASSWORD }}"
  ZO_ETCD_CLIENT_CERT_AUTH: "{{ .Values.config.ZO_ETCD_CLIENT_CERT_AUTH }}"
  ZO_ETCD_TRUSTED_CA_FILE: "{{ .Values.config.ZO_ETCD_TRUSTED_CA_FILE }}"
  ZO_ETCD_CERT_FILE: "{{ .Values.config.ZO_ETCD_CERT_FILE }}"
  ZO_ETCD_KEY_FILE: "{{ .Values.config.ZO_ETCD_KEY_FILE }}"
  ZO_ETCD_DOMAIN_NAME: "{{ .Values.config.ZO_ETCD_DOMAIN_NAME }}"
  ZO_ETCD_LOAD_PAGE_SIZE: "{{ .Values.config.ZO_ETCD_LOAD_PAGE_SIZE }}"
  ZO_SLED_DATA_DIR: "{{ .Values.config.ZO_SLED_DATA_DIR }}"
  ZO_SLED_PREFIX: "{{ .Values.config.ZO_SLED_PREFIX }}"
  ZO_S3_PROVIDER: "{{ .Values.config.ZO_S3_PROVIDER }}"
  {{- if .Values.minio.enabled }}
  ZO_S3_PROVIDER: "minio"
  {{- end }}
  {{- if not .Values.minio.enabled }}
  ZO_S3_SERVER_URL: "{{ .Values.config.ZO_S3_SERVER_URL }}"
  {{- else }}
  ZO_S3_SERVER_URL: "http://{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000"
  {{- end }}
  {{- if not .Values.minio.enabled }}
  ZO_S3_REGION_NAME: "{{ .Values.config.ZO_S3_REGION_NAME }}"
  {{- else }}
  ZO_S3_REGION_NAME: "us-east-1"
  {{- end }}
  {{- if not .Values.minio.enabled }}
  ZO_S3_BUCKET_NAME: "{{ .Values.config.ZO_S3_BUCKET_NAME }}"
  {{- else }}
  ZO_S3_BUCKET_NAME: "{{ (index .Values.minio.buckets 0 ).name }}"
  {{- end }}
  ZO_S3_FEATURE_FORCE_PATH_STYLE: "{{ .Values.config.ZO_S3_FEATURE_FORCE_PATH_STYLE }}"
  ZO_S3_FEATURE_HTTP1_ONLY: "{{ .Values.config.ZO_S3_FEATURE_HTTP1_ONLY }}"
  ZO_S3_FEATURE_HTTP2_ONLY: "{{ .Values.config.ZO_S3_FEATURE_HTTP2_ONLY }}"
  ZO_S3_SYNC_TO_CACHE_INTERVAL: "{{ .Values.config.ZO_S3_SYNC_TO_CACHE_INTERVAL }}"
  ZO_USAGE_REPORTING_ENABLED: "{{ .Values.config.ZO_USAGE_REPORTING_ENABLED }}"
  ZO_USAGE_REPORTING_COMPRESSED_SIZE: "{{ .Values.config.ZO_USAGE_REPORTING_COMPRESSED_SIZE }}"
  ZO_USAGE_ORG: "{{ .Values.config.ZO_USAGE_ORG }}"
  ZO_USAGE_BATCH_SIZE: "{{ .Values.config.ZO_USAGE_BATCH_SIZE }}"
  ZO_PRINT_KEY_CONFIG: "{{ .Values.config.ZO_PRINT_KEY_CONFIG }}"
  ZO_PRINT_KEY_EVENT: "{{ .Values.config.ZO_PRINT_KEY_EVENT }}"
  ZO_PRINT_KEY_SQL: "{{ .Values.config.ZO_PRINT_KEY_SQL }}"
  RUST_LOG: "{{ .Values.config.RUST_LOG }}"
  RUST_BACKTRACE: "{{ .Values.config.RUST_BACKTRACE }}"
  ZO_DYNAMO_META_STORE_ENABLED: "{{ .Values.config.ZO_DYNAMO_META_STORE_ENABLED }}"
